version: '3.8'

services:
  mcp-auth-server:
    build: .
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - identity-server
    networks:
      - mcp-network

  # Example Identity Server (replace with your actual Identity Server)
  identity-server:
    image: identityserver/identityserver4:latest
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - mcp-network

networks:
  mcp-network:
    driver: bridge

# For development with external Identity Server, use this simpler version:
# version: '3.8'
# services:
#   mcp-auth-server:
#     build: .
#     ports:
#       - "8080:8080"
#       - "8081:8081"
#     environment:
#       - ASPNETCORE_ENVIRONMENT=Development
#       - ASPNETCORE_URLS=http://+:8080;https://+:8081
#     volumes:
#       - ./appsettings.Development.json:/app/appsettings.Development.json